# Generated by Django 5.2.3 on 2025-07-04 07:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('REAL_ESTATE', 'Immobilier'), ('STOCKS', 'Actions'), ('BONDS', 'Obligations'), ('INSURANCE', 'Assurance vie'), ('SAVINGS_ACCOUNT', 'Livret A'), ('PENSION_PLAN', 'PEL'), ('CHECKING_ACCOUNT', 'Compte courant'), ('CRYPTO', 'Crypto'), ('PRECIOUS_METALS', 'Or/Métaux'), ('BUSINESS', 'Entreprise'), ('OTHER', 'Autre')], max_length=20)),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_value'],
                'unique_together': {('name', 'user')},
            },
        ),
    ]
